### ISSUE TITLE
Big commerce products are not import properly

### ISSUE THREAD

**Issue by avinashcohaesus** [acquia/acf#6]
Hi,
I would like to import Big-commerce products in my D8.7.1 site. For this I am using following modules:

1. ACF BigCommerce
2. ACF Catalog
3. ACF Demo
4. BC ACF Blocks

'ACF Demo' module is working fine and able to import all demo products successfully But when I import the BC products then only JSON is created and save in D8 but not products.
I added BC credentials in acf_bc module settings page already for connection.

I tried to debug the code and found that no value pass to the $children variable **[line#63  File: /src/form/CatelogImportForm.php]** in case of  BC import and that's why its showing error in log and only Json data save but not products.

When I tried to give static array of product schema to $children variable then its able to import BC products successfully But the issue is why the required data is not coming for $children variable during real BC products import.

Could you please check.

Thanks

**Comment by saltednut** [comment]
Hi - this usually happens when there is some issue with the mapping provided not matching up with what's delivered via json. You may need to extend the existing plugins or write your own for BC based on the examples provided. ACF remains reference architecture, for reasons such as this.

**Comment by rlnorthcutt** [comment]
You will probably need to check that your data matches the catalog.yml config:
https://github.com/thirdandgrove/acf_bc/blob/master/config/install/acf_catalog.catalog.bigcommerce_catalog.yml

As Brant points out, you should almost certainly create your own connector by cloning/renaming the acf_bc module.
