### ISSUE TITLE
Installation directions for acf_demo omit required drupal modules

### ISSUE THREAD

**Issue by ba66e77** [acquia/acf#8]
The [instructions for installing acf_demo](https://github.com/acquia/acf/blob/master/acf_demo/README.md) say it's necessary to `composer require acquia/acf` but, through dependencies, enabling acf_demo requires additional drupal contrib modules to be added. These are not pulled in automatically when composer requiring acquia/acf.

The additional required modules are:
1. basic_data
2. connection
3. simple_api
4. react_block (which pulls in pdb)

Either the composer.json files in the relevant acf_demo modules need to be updated to include the drupal modules the require or the README.md instructions need to be updated to include them in the list that users have to manually include via composer require.

**Comment by rlnorthcutt** [comment]
Thanks! I've updated the demo readme.
